name: Validate and process Building Blocks
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  validate-and-process:
    # Avoid running the workflow on template clone
    if: github.run_number != 1
    name: Validate and process
    uses: opengeospatial/bblocks-postprocess/.github/workflows/validate-and-process.yml@master
    secrets:
      sparql_username: ${{ secrets.sparql_username }}
      sparql_password: ${{ secrets.sparql_password }}
    with:
      before_postprocess: |
        LOCAL_REPOS_DIR=$RUNNER_TEMP/repos/
        mkdir -p $LOCAL_REPOS_DIR
        git clone --depth 1 https://github.com/avillar/ogcapi-sosa.git $LOCAL_REPOS_DIR/sosa
        cat << EOF > bblocks-config-local.yml
        url-mappings:
          'https://opengeospatial.github.io/ogcapi-sosa/': '$LOCAL_REPOS_DIR/sosa/'
        EOF
        cat bblocks-config-local.yml
        find $LOCAL_REPOS_DIR
